In [1]:
%load_ext autoreload
%autoreload 2
%aimport -numpy

from mlp_mark1 import Mlp
import numpy as np

In [2]:
np.random.seed(12)

X = np.array([[0,0],[0,1],[1,0],[1,1]])
D = np.array([-1,1,1,-1])

nn = Mlp([2], X, D)
nn.epochs_n, nn.batch_sz =600, 4
nn.lr, nn.mmtum, nn.reg = 1, 1., .001

nn.train()

print(nn.predict(np.array([1,1])))
print(nn.predict(np.array([0,1])))


[2L, 2, 1L]
a
    0 out of    1, on epoch   599
[[-0.9227975]]
[[ 0.93822671]]


In [2]:
data = np.genfromtxt('../data/mnist_train.csv', delimiter=',')
data = data[1:,:]
print(data.shape)

(42000L, 785L)


In [4]:
data = data[:10000,:]
X = data[:,1:]
D = np.tile(np.arange(10),(data.shape[0],1))
D = np.equal(D,np.tile(data[:,0][:,np.newaxis],(1,10)))*1.

X = X - np.tile(X.mean(axis=0), (X.shape[0],1))
X /= X.max() 

print(X.shape)
print(D.shape)

print(np.hstack([X,D]).shape)

#print(X[:10, 564:574])
print(np.hstack([data[:10,0][:,np.newaxis],D[:10,:]]))

(10000L, 784L)
(10000L, 10L)
(10000L, 794L)
[[ 1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 1.  0.  1.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 4.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  1.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 7.  0.  0.  0.  0.  0.  0.  0.  1.  0.  0.]
 [ 3.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]
 [ 5.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.]
 [ 3.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.]]


In [11]:
nn = Mlp([256, 128, 128], X, D)

nn.epochs_n, nn.batch_sz = 300, 100
nn.lr, nn.mmtum, nn.reg = 0.1, .0, .0001
nn.stopTol = .1

nn.autoencode(128).train().accuracy(X,data[:,0])

[784L, 128, 784L]
a
   99 out of  100, on epoch     5
[128, 256, 128, 128, 10L]
a
   99 out of  100, on epoch     2
[[ 1.  1.]
 [ 0.  0.]
 [ 1.  1.]
 [ 2.  4.]
 [ 0.  0.]
 [ 0.  0.]
 [ 7.  7.]
 [ 3.  3.]
 [ 5.  5.]
 [ 3.  3.]]


0.83250000000000002

In [74]:
def test(l):
    l.append(5)

In [77]:
tmp = []
test(tmp)
tmp

[5]